### PR TITLE
refactor: rebranding, split installation for fe&be

### PR DESCRIPTION
**Pull request by ggurkal**
This PR re-brands the package and splits the installation for FE and the BE, as they need different packages.

Suggestions:
- I believe we should remove FE specific packages from `peerDependencies`
- Replace names. `web` → `fe`, `node` → `be`. Any other suggestions?

### CODE REVIEW

**Comment by mitchelvanbever** [comment]
>     * I believe we should remove FE specific packages from `peerDependencies`
Agreed, I believe we need to review the amount of dependencies needed in the FE anyways 🙈
 
>     * Replace names. `web` → `fe`, `node` → `be`. Any other suggestions?
I still think web / node make sense. We have three configs exported:
1. Libraries or other projects (minimal)
2. Web applications (react specific rules added)
3. Node applications (node specific rules added)

So the only other 'export' name I can think of that would make sense is `react` / `nest` for the web and node package respectively. What do you think?

**Comment by ggurkal** [comment]
It kinda makes sense to rename `web` to `react` as it has really react related dependencies, but that's not the case for the `node` one 🤔

**Comment by mitchelvanbever** [comment]
> It kinda makes sense to rename `web` to `react` as it has really react related dependencies, but that's not the case for the `node` one 🤔

Agreed, does server make more sense? Also if you feel that BE is fitting we can go for that 🤷‍♂️

**Comment by leeuwis** [comment]
I think `react` definitely makes sense, for the other one would either keep it as `node` or use something like `backend` (abbreviating to `be` not super clear imo)

**Comment by mitchelvanbever** [comment]
> I think `backend` fits. `node` is too general, sounds as if it fits to libraries, etc as well

Alright, let's settle for `react` & `backend` 👌

**Review by mitchelvanbever — APPROVED** [review]
it's been a while but that doesn't mean it's not in need of a review 😁 It's LGTM let's ship it when you have some free time 👍

**Pull request merged**
