### PR TITLE
fix(prettier): useTabs: true 🍿

### PR DESCRIPTION
**Pull request by mitchelvanbever**
We discuss this at least once a year but I don't think we've ever actually settled on anything and just keep using spaces. I'm hoping that opening this PR will spark another convo in which we can settle if we're either going for tabs or keep sticking with spaces.

For me personally I've always been on the spaces side until I learned about the accessibility concerns of not using tabs. I've since then converted to tabs completely (existing projects and when starting out new ones). And there are not really any downside (to me), only benefits of being more accessible and giving developers more control on their own dev experience. Having that said you do have to do some customisations yourself as some defaults shipped by companies are pretty out there (I'm looking at you Github with a default of `tabSize: 8`).

Let me know how what ya'll are thinking on the whole thing 👍 

For more context and insights on the matter: [Prettier issue to make it the default](https://github.com/prettier/prettier/issues/7475) (still open, but most are on the fence of not "forcing" this on developers)

### CODE REVIEW

**Comment by leeuwis** [comment]
For some reason I've always been a spaces side as well, but your explanation and the comments in the linked PR make sense to me, especially the accessibility reason. I also can't think of an argument against it except personal preference, so from my perspective we can move forward with this change 👍 

P.S. I did just change my Github "Tab size preference" width to 2 spaces 😄

**Review by leeuwis — APPROVED** [review]

**Comment by gusbueno** [comment]
I was always a tabs person but I've been always forced to use spaces as (I guess) most of the people use spaces.I didn't really know the pros and cons of both sides but I'm happy to read that tabs have some good reasons to be used.

Long live the Tabs!

**Comment by BJvdA** [comment]
I think it's good to change yeah, we should probably add a .editorconfig to the code repos so people don't have to individually change the tabwidth to 2

**Review by BJvdA — APPROVED** [review]

**Review by ggurkal — APPROVED** [review]

**Comment by Maren-Osnabrug** [comment]
I used to be a tabs person, but converted to spaces as it is what most people use. Reading the github thread and reddit post mentioned in there highlights the a11y use case and I would prefer we switch to tabs for that reason 👍

**Pull request merged**
